module.exports = [
    "Genghis Karp",
    "Uncle Salmon",
    "Phish Styx",
    "Tuna Turner",
    "Marlin Monroe",
    "Swim Shady",
    "Bubba",
    "Sushi",
    "Gillbert Godfishy",
    "Pacifisht",
    "Captain Hook",
    "Fish n Chips",
    "James Pond",
    "Mr Bubbles",
    "Leviathan",
    "Gyrados",
    "Bobby Filet",
    "McFish",
    "Mrs Puff",
    "Jaws",
    "Scuba Doo",
    "SeaBastian",
    "Harley Finn",
    "Bob Marlin",
    "Bart"
];